Quiet the update process

diff --git a/etc/cont-init.d/21-update-flexget b/etc/cont-init.d/21-update-flexget
--- a/etc/cont-init.d/21-update-flexget
+++ b/etc/cont-init.d/21-update-flexget
@@ -1,7 +1,22 @@
 #!/usr/bin/with-contenv bash
 
-pip install -U pip
+pip install -U pip > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+	echo "Successfully updated pip"
+else
+	echo "Pip failed to update"
+fi
 # Make sure to install setuptools version >=36 to avoid a race condition, see:
 # https://github.com/pypa/setuptools/issues/951
-pip install -U setuptools>=36
-pip install -U flexget
+pip install -U setuptools>=36 > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+	echo "Successfully updated setuptools"
+else
+	echo "Setuptools failed to update"
+fi
+pip install -U flexget > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+	echo "Successfully installed flexget"
+else
+	echo "Flexget failed to install"
+fi
diff --git a/etc/cont-init.d/22-update-transmission b/etc/cont-init.d/22-update-transmission
--- a/etc/cont-init.d/22-update-transmission
+++ b/etc/cont-init.d/22-update-transmission
@@ -1,5 +1,10 @@
 #!/usr/bin/with-contenv bash
 
 if [ -z "$TORRENT_PLUGIN" ] || [[ "$TORRENT_PLUGIN" == *"transmission"* ]]; then
-    pip install -U transmissionrpc
+    pip install -U transmissionrpc > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+	echo "Successfully updated transmission"
+else
+	echo "Transmission failed to update"
+fi
 fi
